name: tiny
input_size: 64
image_size: 64
input_channels: 3
stem_channels: [3, 8, 16]
stage_config:
  stage1:
    in_channels: 16
    mid_channels: 8
    out_channels: 24
    num_blocks: 1
    num_layers: 2
    kernel_size: 3
    downsample: false
    use_light_conv: false
  stage2:
    in_channels: 24
    mid_channels: 12
    out_channels: 32
    num_blocks: 1
    num_layers: 2
    kernel_size: 3
    downsample: true
    use_light_conv: false
  stage3:
    in_channels: 32
    mid_channels: 16
    out_channels: 48
    num_blocks: 2
    num_layers: 2
    kernel_size: 5
    downsample: true
    use_light_conv: true
  stage4:
    in_channels: 48
    mid_channels: 24
    out_channels: 64
    num_blocks: 1
    num_layers: 2
    kernel_size: 5
    downsample: true
    use_light_conv: true
hidden_size: 64
encoder_hidden_size: 64
activation: relu
batch_norm_eps: 1.0e-5
initialization: pytorch_default

decoder_hidden_size: 32
decoder_layers: 1
decoder_attention_heads: 4
decoder_ffn_dim: 64
max_position_embeddings: 32
vocab_size: 687
bos_token_id: 0
pad_token_id: 1
eos_token_id: 2
unk_token_id: 3
decoder_start_token_id: 0
decoder_dropout: 0.0
decoder_attention_dropout: 0.0
decoder_activation_dropout: 0.0
decoder_layer_norm_eps: 1.0e-5
decoder_scale_embedding: true
tie_word_embeddings: false
